package main.settingsWindow;

public enum SettingsFlag {
    CONSTANTS,

    IMAGES,

    ORIGINAL_IMAGES__BUTTON,
    ORIGINAL_IMAGES__CLOSED_TILES,
    ORIGINAL_IMAGES__OPENED_TILES,
    ORIGINAL_IMAGES__SETTINGS_CHECKER_FLAGS,
    ORIGINAL_IMAGES__TIME,

    RESIZED_IMAGES__BUTTON,
    RESIZED_IMAGES__CLOSED_TILES,
    RESIZED_IMAGES__OPENED_TILES,
    RESIZED_IMAGES__SETTINGS_CHECKER_FLAGS,
    RESIZED_IMAGES__TIME,

    SETTINGS_LOGS,
    DEFAULT_SETTINGS,
    CUSTOM_SETTINGS

}
